version: '3'

services:
  db:
    image: mysql:5.6
    volumes:
      - ./docker/dumps:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: application
      MYSQL_DATABASE: application
      MYSQL_USER: application
      MYSQL_PASSWORD: application
  application:
    depends_on:
      - db
      - php
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8088:8088
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: application
  php:
    image: miron/php7-typo3:7.3
    restart: always
    environment:
      XDEBUG_CONFIG: remote_port=9002 remote_connect_back=0 idekey=PHPSTORM remote_host=host.docker.internal remote_enable=1
    expose:
      - "9000"
    ports:
      - "9001:9001"
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
